import { nationalSvg } from "./nationalSvg";
import { sampleSvg } from "./sampleSvg";
export function mapDocument(
  key: string,
  initial: { lat: number; lng: number; zoom: number },
) {
  const config = JSON.stringify({ key, ...initial }).replace(/</g, "\\u003c");
  const bg = JSON.stringify(
    `data:image/svg+xml;charset=utf-8,${encodeURIComponent(sampleSvg)}`,
  ).replace(/</g, "\\u003c");
  const nation = JSON.stringify(
    `data:image/svg+xml;charset=utf-8,${encodeURIComponent(nationalSvg)}`,
  ).replace(/</g, "\\u003c");
  return `<!DOCTYPE html><html lang="ko"><head><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><style>html,body,#map{height:100%;width:100%;margin:0;overflow:hidden}body{font-family:Pretendard,-apple-system,sans-serif;background:#DCE8E6}#map{position:relative;touch-action:none}#background{position:absolute;pointer-events:none;max-width:none}#markers{position:absolute;inset:0;pointer-events:none}.marker{position:absolute;transform:translate(-50%,-100%);pointer-events:auto;border-radius:10px;border:1.5px solid var(--color);padding:0;background:white;box-shadow:0 2px 5px #0003;white-space:nowrap;cursor:pointer;font:600 13px/1.35 inherit;color:#2A2A28}.marker .amount{background:var(--color);color:white;font-size:14px;font-weight:700;padding:3px 8px;border-radius:8px 8px 0 0}.marker .sub{padding:2px 7px 3px;font-size:11px}.marker:after{content:'';position:absolute;bottom:-7px;left:calc(50% - 5px);border-left:6px solid transparent;border-right:6px solid transparent;border-top:7px solid var(--color)}.marker.region{transform:translate(-50%,-50%);border:2px solid white;border-radius:12px;background:var(--color);color:white;padding:5px 11px 6px;text-align:center}.region:after{display:none}.region .amount{padding:1px 0}.region .sub{padding:0}.dot{width:14px;height:14px;border:2px solid white;border-radius:50%;background:var(--color);padding:0;transform:translate(-50%,-50%)}.dot:after{display:none}.marker.selected{--color:#111110!important;z-index:100;scale:1.08}#note{position:absolute;left:8px;bottom:8px;background:#ffffffdd;border-radius:5px;padding:3px 6px;font-size:11px;color:#5A5A55;pointer-events:none}#error{position:absolute;inset:30% 12%;background:white;border-radius:12px;padding:20px;display:none;z-index:150;text-align:center;font-size:16px}</style></head><body><div id="map"><img id="background" alt="샘플 지도"><div id="places" style="position:absolute;inset:0;pointer-events:none"></div><div id="markers"></div><span id="note"></span><div id="error"></div></div><script>
(function(){const config=${config};let map=null,overlays=[],data={markers:[],property:'apartment',unit:'평',selected:null},camera={lat:config.lat,lng:config.lng,zoom:config.zoom},drag=null,animation=null,zoomTarget=null,zoomLock=0;const el=document.getElementById('map'),bg=document.getElementById('background'),layer=document.getElementById('markers'),note=document.getElementById('note');
function send(m){const s=JSON.stringify(m);if(window.ReactNativeWebView)window.ReactNativeWebView.postMessage(s);else window.parent.postMessage(m,'*');}
function price(v){if(v==null)return '정보 없음';return v>=1e8?(v/1e8).toFixed(1).replace(/\\.0$/,'')+'억':Math.round(v/1e4).toLocaleString('ko-KR')+'만';}
function man(v){return v==null?'—':Math.round(v/1e4).toLocaleString('ko-KR');}
function bounds(){if(map){const b=map.getBounds(),a=b.getSouthWest(),c=b.getNorthEast();return [a.getLng(),a.getLat(),c.getLng(),c.getLat()];}const span=.055*Math.pow(2,14-camera.zoom),ratio=el.clientWidth/Math.max(1,el.clientHeight);return [camera.lng-span*ratio/2,camera.lat-span/2,camera.lng+span*ratio/2,camera.lat+span/2];}
function project(m){if(map){const p=map.getProjection().containerPointFromCoords(new kakao.maps.LatLng(m.lat,m.lng));return {x:p.x,y:p.y};}const b=bounds();return {x:(m.lng-b[0])/(b[2]-b[0])*el.clientWidth,y:(b[3]-m.lat)/(b[3]-b[1])*el.clientHeight};}
function emit(){if(map){const c=map.getCenter();camera={lat:c.getLat(),lng:c.getLng(),zoom:18-map.getLevel()};}send({...camera,type:'camera',bbox:bounds()});render();}
function render(){overlays.forEach(o=>o.setMap(null));overlays=[];layer.replaceChildren();if(!map){const b=bounds(),local=camera.zoom>=11&&camera.lat>=34.85&&camera.lat<=35.4&&camera.lng>=128.75&&camera.lng<=129.35;
const west=local?128.8:119,north=local?35.4:46,unit=local?.00025:.01,scale=el.clientWidth/((b[2]-b[0])/unit),src=local?${bg}:${nation};
if(bg.getAttribute('src')!==src)bg.src=src;bg.style.width=(2000*scale)+'px';bg.style.height=((local?1600:2000)*scale)+'px';bg.style.left=(-(b[0]-west)/unit*scale)+'px';bg.style.top=(-(north-b[3])/unit*scale)+'px';
const places=document.getElementById('places');places.replaceChildren();if(!local&&camera.zoom<11)[['서울',37.566,126.978],['인천',37.456,126.705],['대전',36.35,127.385],['대구',35.871,128.601],['광주',35.159,126.853],['부산',35.18,129.075],['제주',33.499,126.531],['울릉도',37.48,130.90],['독도',37.24,131.87]].forEach(([name,lat,lng])=>{const pos=project({lat,lng});const label=document.createElement('div');label.textContent=name;label.style.cssText='position:absolute;font-size:11px;color:#4C5C62;font-weight:600;white-space:nowrap;transform:translate(-50%,-50%);text-shadow:0 0 3px white,0 0 3px white;';label.style.left=pos.x+'px';label.style.top=pos.y+'px';places.appendChild(label);});}

const color={apartment:'#3E64A0',officetel:'#7B5A9E',villa:'#B0506B',land:'#4F7A3A'}[data.property];const rects=[];
[...data.markers].sort((a,b)=>(id(b)===data.selected)-(id(a)===data.selected)||(b.kind==='region')-(a.kind==='region')||(b.transaction_count||0)-(a.transaction_count||0)).forEach(m=>{const p=project(m);if(p.x<-100||p.x>el.clientWidth+100||p.y<-100||p.y>el.clientHeight+100)return;const l=m.latest,s=m.summary;let amount='',sub='',name='';if(m.kind==='region'){name=m.name;amount=s.median_price_per_pyeong!=null?'평당 '+price(s.median_price_per_pyeong):s.median_deposit_per_pyeong!=null?'평당 보증금 '+price(s.median_deposit_per_pyeong):'보증금 '+man(s.median_deposit)+' · 월 '+man(s.median_monthly_rent);sub=m.transaction_count.toLocaleString()+'건';}else{amount=l.deal_type==='sale'?price(l.price):l.deal_type==='jeonse'?'전세 '+price(l.deposit):man(l.deposit)+'/'+man(l.monthly_rent);let area=l.land_area_pyeong!=null?l.land_area_pyeong:l.supply_area_pyeong!=null?l.supply_area_pyeong:l.exclusive_area_pyeong;sub=(l.supply_area_pyeong==null&&l.land_area_pyeong==null?'전용 ':'')+(area==null?'—':data.unit==='㎡'?(area*3.3058).toFixed(1):area)+data.unit+" · '"+l.contract_date.slice(2,7).replace('-','.');}
const button=document.createElement('button');button.className='marker '+(m.kind==='region'?'region ':'')+(id(m)===data.selected?'selected':'');button.style.setProperty('--color',color);button.setAttribute('aria-label',(name||m.name||'토지')+' '+amount);[name,amount,sub].forEach((txt,i)=>{if(!txt)return;const d=document.createElement('div');d.className=i===1?'amount':'sub';d.textContent=txt;button.appendChild(d);});button.style.left=p.x+'px';button.style.top=p.y+'px';layer.appendChild(button);const r=button.getBoundingClientRect();const collision=rects.some(a=>r.left<a.right+3&&r.right>a.left-3&&r.top<a.bottom+3&&r.bottom>a.top-3);if(collision&&id(m)!==data.selected){button.className='marker dot';button.replaceChildren();button.setAttribute('aria-label',(m.name||'마커')+' 확대');}else rects.push(r);button.onclick=e=>{e.stopPropagation();if(button.classList.contains('dot')){move({lat:m.lat,lng:m.lng,zoom:camera.zoom});zoom(1);}else send({type:'marker',id:id(m)});};if(map){button.style.position='relative';button.style.left='';button.style.top='';button.style.transform='none';const o=new kakao.maps.CustomOverlay({position:new kakao.maps.LatLng(m.lat,m.lng),content:button,yAnchor:m.kind==='region'?.5:1,zIndex:id(m)===data.selected?100:10});o.setMap(map);overlays.push(o);}});}
function id(m){return m.region_code||m.complex_id||m.transaction_id;}
function move(c){clearTimeout(animation);zoomTarget=null;if(map){if(c.bbox){const b=c.bbox;map.setBounds(new kakao.maps.LatLngBounds(new kakao.maps.LatLng(b[1],b[0]),new kakao.maps.LatLng(b[3],b[2])));}else{map.setLevel(Math.max(1,Math.min(14,Math.round(18-(c.zoom||camera.zoom)))),{animate:{duration:320}});map.panTo(new kakao.maps.LatLng(c.lat??camera.lat,c.lng??camera.lng));}}else{camera={lat:c.lat??camera.lat,lng:c.lng??camera.lng,zoom:c.zoom??camera.zoom};if(c.bbox){camera.lat=(c.bbox[1]+c.bbox[3])/2;camera.lng=(c.bbox[0]+c.bbox[2])/2;camera.zoom=14-Math.log2((c.bbox[3]-c.bbox[1])/.055);}emit();}}
function zoom(delta,amount=.25){if(map){if(Date.now()<zoomLock)return;zoomLock=Date.now()+320;map.setLevel(Math.max(1,Math.min(14,map.getLevel()-Math.sign(delta))),{animate:{duration:320}});return;}
clearTimeout(animation);const from=camera.zoom,target=Math.max(4,Math.min(17,(zoomTarget??from)+Math.sign(delta)*amount)),start=Date.now();zoomTarget=target;function frame(){const t=Math.min(1,(Date.now()-start)/240),ease=1-Math.pow(1-t,3);camera.zoom=from+(target-from)*ease;render();if(t<1)animation=setTimeout(frame,16);else{zoomTarget=null;emit();}}frame();}
function receive(m){if(m.type==='state'){data={...data,...m};if(map){const next=data.base==='satellite'?kakao.maps.MapTypeId.HYBRID:kakao.maps.MapTypeId.ROADMAP;if(map.getMapTypeId()!==next)map.setMapTypeId(next);if(map.__cad!==data.cadastral){if(data.cadastral)map.addOverlayMapTypeId(kakao.maps.MapTypeId.USE_DISTRICT);else map.removeOverlayMapTypeId(kakao.maps.MapTypeId.USE_DISTRICT);map.__cad=data.cadastral;}}render();}if(m.type==='move')move(m);if(m.type==='zoom')zoom(m.delta);}
window.addEventListener('message',e=>{if(e.source&&e.source!==window.parent)return;try{receive(typeof e.data==='string'?JSON.parse(e.data):e.data);}catch{}});document.addEventListener('message',e=>{try{receive(JSON.parse(e.data));}catch{}});window.pugurinReceive=receive;
function sample(){bg.src=${bg};note.textContent='샘플 지도 · 카카오맵 키 미설정';el.onpointerdown=e=>{if(e.target.closest('button'))return;clearTimeout(animation);zoomTarget=null;el.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,lat:camera.lat,lng:camera.lng,moved:false};};el.onpointermove=e=>{if(!drag)return;const b=bounds(),dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>5)drag.moved=true;camera.lng=drag.lng-dx/el.clientWidth*(b[2]-b[0]);camera.lat=drag.lat+dy/el.clientHeight*(b[3]-b[1]);render();};el.onpointerup=()=>{if(drag&&!drag.moved)send({type:'mapClick'});drag=null;emit();};el.onwheel=e=>{e.preventDefault();zoom(e.deltaY<0?1:-1,.12);};send({type:'ready'});emit();}
function fail(){const err=document.getElementById('error');err.style.display='block';err.textContent='카카오 지도를 불러올 수 없어요. 네트워크와 지도 키의 등록 도메인을 확인해 주세요.';send({type:'error',message:err.textContent});}
if(!config.key)sample();else{note.textContent='';bg.style.display='none';const script=document.createElement('script');script.src='https://dapi.kakao.com/v2/maps/sdk.js?autoload=false&appkey='+encodeURIComponent(config.key);script.onerror=fail;const timeout=setTimeout(fail,12000);script.onload=()=>{try{kakao.maps.load(()=>{clearTimeout(timeout);map=new kakao.maps.Map(el,{center:new kakao.maps.LatLng(camera.lat,camera.lng),level:Math.round(18-camera.zoom)});kakao.maps.event.addListener(map,'idle',emit);kakao.maps.event.addListener(map,'click',()=>send({type:'mapClick'}));send({type:'ready'});emit();});}catch{clearTimeout(timeout);fail();}};document.head.appendChild(script);}
window.addEventListener('resize',()=>{if(map)map.relayout();emit();});})();</script></body></html>`;
}
